/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    "intro",
    "graphq-vs-dql",
    {
      "Data Modeling": [
        "modeling-overview",
        "type-fields",
        "edge-predicates",
        "identification",
        "interfaces-unions",
        {
          Advanced: ["data-storage", "dql-mapping", "distribution", "facets"],
        },
      ],
    },
    {
      Directives: [
        "directives",
        "schema-directives",
        "client-directives",
        {
          Advanced: ["cascade"],
        },
      ],
    },
    "generating-filters",
    "maintaining-relationships",
    {
      "Querying Data": [
        "query-syntax",
        "select-one",
        "select-many",
        {
          Advanced: ["password-check", "custom-queries"],
        },
      ],
    },
    {
      "Mutating Data": [
        "mutation-syntax",
        "create-nodes",
        "update-nodes",
        "delete-nodes",
      ],
    },
    "fragments",
    {
      "Beyond the Basics": [
        "subscriptions",
        "hiding-operations",
        {
          "Authentication/Authorization": [
            "jwt",
            "rbac-auth",
            "abac-auth",
            "gbac-auth",
            "combining-auth-rules",
            "role-less-auth",
            {
              "Authentication Services": [
                "custom-auth",
                "auth0",
                "firebase-auth",
              ],
            },
          ],
        },
        "lambdas",
        "external-data",
        "hooking-mutations",
        "remapping-fields",
        "language-support",
        {
          Gotchas: [
            "non-unique-xid",
            "set-vs-array",
            "required-lists",
            "reverse-inverse",
          ],
        },
      ],
    },
    {
      "The Missing Features": [
        "nested-filtering",
        "post-update-auth",
        "deep-mutations",
        "field-level-auth",
        "facets",
      ],
    },
    {
      "Community Recommendations": [
        {
          Frameworks: ["react", "next-js", "sveltekit", "angular"],
        },
        {
          "GraphQL Clients": [
            {
              Javascript: ["apollo-client", "urql", "j-dgraph", "easy-dgraph"],
            },
          ],
        },
        {
          "GraphQL Tools": [
            "dgraph-cloud",
            "apollo-studio",
            "graphql-playground",
            "graphiql",
            "insomnia",
          ],
        },
        {
          Visualizers: ["ratel", "sigma-js", "constellation", "d3"],
        },
      ],
    },
    "useful-links",
    "defs",
  ],
};

module.exports = sidebars;
